language: node_js
node_js:
  - 'stable'

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm install

before_script:
  - npm run build
  - npm start -- --silent &

script:
  - npm run ci:cypress-run
  - npm test
  - npm run deploy
