const USER = '@user'

export const USER_REQUEST_LOAD = `${USER}/REQUEST_LOAD`
export const USER_REQUEST_SUCCESS = `${USER}/REQUEST_SUCCESS`
export const USER_REQUEST_ERROR = `${USER}/REQUEST_ERROR`
export const USER_IS_LOADING = `${USER}/IS_LOADING`
export const USER_RESET = `${USER}/RESET`

const REPOSITORIES = '@repositories'

export const REPOSITORIES_REQUEST_LOAD = `${REPOSITORIES}/REQUEST_LOAD`
export const REPOSITORIES_REQUEST_SUCCESS = `${REPOSITORIES}/REQUEST_SUCCESS`
export const REPOSITORIES_REQUEST_ERROR = `${REPOSITORIES}/REQUEST_ERROR`
export const REPOSITORIES_IS_LOADING = `${REPOSITORIES}/IS_LOADING`
